// protoc --go_out=internal/infrastructure/client/friendclient/. --go-grpc_out=internal/infrastructure/client/friendclient/. internal/infrastructure/client/friendclient/proto/friend.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: internal/infrastructure/client/friendclient/proto/friend.proto

package friendclient

import (
	_ "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFriendshipStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId string `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
}

func (x *GetFriendshipStatusRequest) Reset() {
	*x = GetFriendshipStatusRequest{}
	mi := &file_internal_infrastructure_client_friendclient_proto_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendshipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendshipStatusRequest) ProtoMessage() {}

func (x *GetFriendshipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_client_friendclient_proto_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendshipStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFriendshipStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDescGZIP(), []int{0}
}

func (x *GetFriendshipStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFriendshipStatusRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type GetFriendshipStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IsSender  bool   `protobuf:"varint,3,opt,name=is_sender,json=isSender,proto3" json:"is_sender,omitempty"`
	Error     string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetFriendshipStatusResponse) Reset() {
	*x = GetFriendshipStatusResponse{}
	mi := &file_internal_infrastructure_client_friendclient_proto_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendshipStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendshipStatusResponse) ProtoMessage() {}

func (x *GetFriendshipStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_client_friendclient_proto_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendshipStatusResponse.ProtoReflect.Descriptor instead.
func (*GetFriendshipStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDescGZIP(), []int{1}
}

func (x *GetFriendshipStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetFriendshipStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetFriendshipStatusResponse) GetIsSender() bool {
	if x != nil {
		return x.IsSender
	}
	return false
}

func (x *GetFriendshipStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_infrastructure_client_friendclient_proto_friend_proto protoreflect.FileDescriptor

var file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5b, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x7b, 0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28,
	0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDescOnce sync.Once
	file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDescData = file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDesc
)

func file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDescData)
	})
	return file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDescData
}

var file_internal_infrastructure_client_friendclient_proto_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_infrastructure_client_friendclient_proto_friend_proto_goTypes = []any{
	(*GetFriendshipStatusRequest)(nil),  // 0: friendclient.GetFriendshipStatusRequest
	(*GetFriendshipStatusResponse)(nil), // 1: friendclient.GetFriendshipStatusResponse
}
var file_internal_infrastructure_client_friendclient_proto_friend_proto_depIdxs = []int32{
	0, // 0: friendclient.FriendService.GetFriendshipStatus:input_type -> friendclient.GetFriendshipStatusRequest
	1, // 1: friendclient.FriendService.GetFriendshipStatus:output_type -> friendclient.GetFriendshipStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_client_friendclient_proto_friend_proto_init() }
func file_internal_infrastructure_client_friendclient_proto_friend_proto_init() {
	if File_internal_infrastructure_client_friendclient_proto_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_client_friendclient_proto_friend_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_client_friendclient_proto_friend_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_client_friendclient_proto_friend_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_client_friendclient_proto_friend_proto = out.File
	file_internal_infrastructure_client_friendclient_proto_friend_proto_rawDesc = nil
	file_internal_infrastructure_client_friendclient_proto_friend_proto_goTypes = nil
	file_internal_infrastructure_client_friendclient_proto_friend_proto_depIdxs = nil
}
