// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package chat

import (
	"github.com/F0urward/proftwist-backend/config"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/broker/kafka"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/authclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/chatclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/friendclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/gigachatclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/postgres"
	"github.com/F0urward/proftwist-backend/internal/server/grpc"
	"github.com/F0urward/proftwist-backend/internal/server/http"
	logging2 "github.com/F0urward/proftwist-backend/internal/server/interceptor/logging"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/auth"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/cors"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/logging"
	"github.com/F0urward/proftwist-backend/internal/server/ws"
	http3 "github.com/F0urward/proftwist-backend/internal/server/ws/http"
	"github.com/F0urward/proftwist-backend/internal/worker"
	"github.com/F0urward/proftwist-backend/pkg/logger"
	kafka3 "github.com/F0urward/proftwist-backend/services/bot/delivery/broker"
	repository2 "github.com/F0urward/proftwist-backend/services/bot/repository"
	"github.com/F0urward/proftwist-backend/services/bot/usecase"
	grpc2 "github.com/F0urward/proftwist-backend/services/chat/delivery/grpc"
	http2 "github.com/F0urward/proftwist-backend/services/chat/delivery/http"
	ws2 "github.com/F0urward/proftwist-backend/services/chat/delivery/ws"
	"github.com/F0urward/proftwist-backend/services/chat/repository"
	"github.com/F0urward/proftwist-backend/services/chat/usecase"
	kafka2 "github.com/F0urward/proftwist-backend/services/notification/delivery/broker"
	usecase2 "github.com/F0urward/proftwist-backend/services/notification/usecase"
)

// Injectors from wire.go:

func InitializeChatWsServer(cfg *config.Config, log logger.Logger) *ws.WsServer {
	db := postgres.NewDatabase(cfg)
	chatRepository := repository.NewChatPostgresRepository(db)
	notificationPublisher := ProvideNotificationPublisher(cfg)
	botPublisher := ProvideBotPublisher(cfg)
	authServiceClient := authclient.NewAuthClient(cfg)
	friendServiceClient := friendclient.NewFriendClient(cfg)
	chatUsecase := usecase.NewChatUsecase(chatRepository, notificationPublisher, botPublisher, authServiceClient, friendServiceClient, cfg)
	wsHandlers := ws2.NewChatWsHandlers(chatUsecase)
	wsRegistrar := ws2.NewChatWsRegistrar(wsHandlers)
	v := AllWsRegistrars(wsRegistrar)
	wsServer := ws.New(cfg, log, v...)
	return wsServer
}

func InitializeChatHttpServer(cfg *config.Config, wsServer *ws.WsServer, log logger.Logger) *http.HttpServer {
	authServiceClient := authclient.NewAuthClient(cfg)
	authMiddleware := auth.NewAuthMiddleware(authServiceClient, cfg)
	corsMiddleware := cors.NewCORSMiddleware(cfg)
	loggingMiddleware := logging.NewLoggingMiddleware(log)
	db := postgres.NewDatabase(cfg)
	chatRepository := repository.NewChatPostgresRepository(db)
	notificationPublisher := ProvideNotificationPublisher(cfg)
	botPublisher := ProvideBotPublisher(cfg)
	friendServiceClient := friendclient.NewFriendClient(cfg)
	chatUsecase := usecase.NewChatUsecase(chatRepository, notificationPublisher, botPublisher, authServiceClient, friendServiceClient, cfg)
	handlers := http2.NewChatHandler(chatUsecase)
	webSocketHandler := http3.NewWebSocketHandler(wsServer)
	v := AllHttpRegistrars(handlers, webSocketHandler)
	httpServer := http.New(cfg, authMiddleware, corsMiddleware, loggingMiddleware, v...)
	return httpServer
}

func InitializeChatGrpcServer(cfg *config.Config, wsServer *ws.WsServer, log logger.Logger) *grpc.GrpcServer {
	loggingUnaryServerInterceptor := logging2.NewLoggingUnaryServerInterceptor(log)
	db := postgres.NewDatabase(cfg)
	chatRepository := repository.NewChatPostgresRepository(db)
	notificationPublisher := ProvideNotificationPublisher(cfg)
	botPublisher := ProvideBotPublisher(cfg)
	authServiceClient := authclient.NewAuthClient(cfg)
	friendServiceClient := friendclient.NewFriendClient(cfg)
	chatUsecase := usecase.NewChatUsecase(chatRepository, notificationPublisher, botPublisher, authServiceClient, friendServiceClient, cfg)
	chatServiceServer := grpc2.NewChatServer(chatUsecase)
	grpcRegistrar := grpc2.NewChatGrpcRegistrar(chatServiceServer)
	v := AllGrpcRegistrars(grpcRegistrar)
	grpcServer := grpc.New(cfg, loggingUnaryServerInterceptor, v...)
	return grpcServer
}

func InitializeNotificationWorker(cfg *config.Config, wsServer *ws.WsServer) *worker.NotificationWorker {
	consumerConfig := ProvideNotificationConsumerConfig(cfg)
	consumer := kafka.NewConsumer(consumerConfig)
	notificationUsecase := usecase2.NewNotificationUsecase(wsServer)
	handlers := kafka2.NewNotificationHandlers(notificationUsecase)
	notificationWorker := worker.NewNotificationWorker(consumer, handlers)
	return notificationWorker
}

func InitializeBotWorker(cfg *config.Config) *worker.BotWorker {
	consumerConfig := ProvideBotConsumerConfig(cfg)
	consumer := kafka.NewConsumer(consumerConfig)
	client := gigachatclient.NewGigaChatClient(cfg)
	gigachatWebapi := repository2.NewGigachatWebapi(client)
	chatServiceClient := chatclient.NewChatClient(cfg)
	botUsecase := bot.NewBotUsecase(gigachatWebapi, chatServiceClient, cfg)
	handlers := kafka3.NewBotHandlers(botUsecase)
	botWorker := worker.NewBotWorker(consumer, handlers)
	return botWorker
}
