// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package chat

import (
	"github.com/F0urward/proftwist-backend/config"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/authclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/postgres"
	"github.com/F0urward/proftwist-backend/internal/server/grpc"
	"github.com/F0urward/proftwist-backend/internal/server/http"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/auth"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/cors"
	"github.com/F0urward/proftwist-backend/internal/server/ws"
	http3 "github.com/F0urward/proftwist-backend/internal/server/ws/http"
	"github.com/F0urward/proftwist-backend/services/chat/adapter"
	grpc2 "github.com/F0urward/proftwist-backend/services/chat/delivery/grpc"
	http2 "github.com/F0urward/proftwist-backend/services/chat/delivery/http"
	"github.com/F0urward/proftwist-backend/services/chat/delivery/ws"
	"github.com/F0urward/proftwist-backend/services/chat/repository"
	"github.com/F0urward/proftwist-backend/services/chat/usecase"
)

// Injectors from wire.go:

func InitializeChatWsServer(cfg *config.Config) *websocket.WsServer {
	wsServer := websocket.New(cfg)
	return wsServer
}

func IntitializeChatWsRegistrar(cfg *config.Config, wsServer *websocket.WsServer) *ws.ChatWsRegistrar {
	db := postgres.NewDatabase(cfg)
	chatRepository := repository.NewChatPostgresRepository(db)
	notifier := chat.NewWSNotifier(wsServer)
	authServiceClient := authclient.NewAuthClient(cfg)
	chatUsecase := usecase.NewChatUsecase(chatRepository, notifier, authServiceClient)
	wsHandlers := ws.NewChatWSHandlers(chatUsecase, wsServer)
	chatWsRegistrar := ws.NewChatWsRegistrar(wsHandlers)
	return chatWsRegistrar
}

func InitializeChatHttpServer(cfg *config.Config, wsServer *websocket.WsServer) *http.HttpServer {
	authServiceClient := authclient.NewAuthClient(cfg)
	authMiddleware := auth.NewAuthMiddleware(authServiceClient, cfg)
	corsMiddleware := cors.NewCORSMiddleware(cfg)
	db := postgres.NewDatabase(cfg)
	chatRepository := repository.NewChatPostgresRepository(db)
	notifier := chat.NewWSNotifier(wsServer)
	chatUsecase := usecase.NewChatUsecase(chatRepository, notifier, authServiceClient)
	handlers := http2.NewChatHandler(chatUsecase)
	webSocketHandler := http3.NewWebSocketHandler(wsServer)
	v := AllHttpRegistrars(handlers, webSocketHandler)
	httpServer := http.New(cfg, authMiddleware, corsMiddleware, v...)
	return httpServer
}

func InitializeChatGrpcServer(cfg *config.Config, wsServer *websocket.WsServer) *grpc.GrpcServer {
	db := postgres.NewDatabase(cfg)
	chatRepository := repository.NewChatPostgresRepository(db)
	notifier := chat.NewWSNotifier(wsServer)
	authServiceClient := authclient.NewAuthClient(cfg)
	chatUsecase := usecase.NewChatUsecase(chatRepository, notifier, authServiceClient)
	chatServiceServer := grpc2.NewChatServer(chatUsecase)
	grpcRegistrar := grpc2.NewChatGrpcRegistrar(chatServiceServer)
	v := AllGrpcRegistrars(grpcRegistrar)
	grpcServer := grpc.New(cfg, v...)
	return grpcServer
}
