version: 2

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell 

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
