// protoc --go_out=internal/infrastructure/client/roadmapinfoclient/. --go-grpc_out=internal/infrastructure/client/roadmapinfoclient/. internal/infrastructure/client/roadmapinfoclient/proto/roadmapinfo.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: internal/infrastructure/client/roadmapinfoclient/proto/roadmapinfo.proto

package roadmapinfoclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoadmapInfoService_GetByRoadmapID_FullMethodName = "/roadmapinfoclient.RoadmapInfoService/GetByRoadmapID"
)

// RoadmapInfoServiceClient is the client API for RoadmapInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoadmapInfoServiceClient interface {
	GetByRoadmapID(ctx context.Context, in *GetByRoadmapIDRequest, opts ...grpc.CallOption) (*GetByRoadmapIDResponse, error)
}

type roadmapInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoadmapInfoServiceClient(cc grpc.ClientConnInterface) RoadmapInfoServiceClient {
	return &roadmapInfoServiceClient{cc}
}

func (c *roadmapInfoServiceClient) GetByRoadmapID(ctx context.Context, in *GetByRoadmapIDRequest, opts ...grpc.CallOption) (*GetByRoadmapIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByRoadmapIDResponse)
	err := c.cc.Invoke(ctx, RoadmapInfoService_GetByRoadmapID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoadmapInfoServiceServer is the server API for RoadmapInfoService service.
// All implementations must embed UnimplementedRoadmapInfoServiceServer
// for forward compatibility.
type RoadmapInfoServiceServer interface {
	GetByRoadmapID(context.Context, *GetByRoadmapIDRequest) (*GetByRoadmapIDResponse, error)
	mustEmbedUnimplementedRoadmapInfoServiceServer()
}

// UnimplementedRoadmapInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoadmapInfoServiceServer struct{}

func (UnimplementedRoadmapInfoServiceServer) GetByRoadmapID(context.Context, *GetByRoadmapIDRequest) (*GetByRoadmapIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByRoadmapID not implemented")
}
func (UnimplementedRoadmapInfoServiceServer) mustEmbedUnimplementedRoadmapInfoServiceServer() {}
func (UnimplementedRoadmapInfoServiceServer) testEmbeddedByValue()                            {}

// UnsafeRoadmapInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoadmapInfoServiceServer will
// result in compilation errors.
type UnsafeRoadmapInfoServiceServer interface {
	mustEmbedUnimplementedRoadmapInfoServiceServer()
}

func RegisterRoadmapInfoServiceServer(s grpc.ServiceRegistrar, srv RoadmapInfoServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoadmapInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoadmapInfoService_ServiceDesc, srv)
}

func _RoadmapInfoService_GetByRoadmapID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByRoadmapIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoadmapInfoServiceServer).GetByRoadmapID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoadmapInfoService_GetByRoadmapID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoadmapInfoServiceServer).GetByRoadmapID(ctx, req.(*GetByRoadmapIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoadmapInfoService_ServiceDesc is the grpc.ServiceDesc for RoadmapInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoadmapInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roadmapinfoclient.RoadmapInfoService",
	HandlerType: (*RoadmapInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByRoadmapID",
			Handler:    _RoadmapInfoService_GetByRoadmapID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/infrastructure/client/roadmapinfoclient/proto/roadmapinfo.proto",
}
