// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package material

import (
	"github.com/F0urward/proftwist-backend/config"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/authclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/postgres"
	"github.com/F0urward/proftwist-backend/internal/server/http"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/auth"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/cors"
	http2 "github.com/F0urward/proftwist-backend/services/material/delivery/http"
	"github.com/F0urward/proftwist-backend/services/material/repository"
	"github.com/F0urward/proftwist-backend/services/material/usecase"
)

// Injectors from wire.go:

func InitializeMaterialHttpServer(cfg *config.Config) *http.HttpServer {
	authServiceClient := authclient.NewAuthClient(cfg)
	authMiddleware := auth.NewAuthMiddleware(authServiceClient, cfg)
	corsMiddleware := cors.NewCORSMiddleware(cfg)
	db := postgres.NewDatabase(cfg)
	materialRepository := repository.NewMaterialPostgresRepository(db)
	materialUsecase := usecase.NewMaterialUsecase(materialRepository, authServiceClient)
	handlers := http2.NewMaterialHandlers(materialUsecase)
	httpRegistrar := http2.NewMaterialHttpRegistrar(handlers)
	v := AllHttpRegistrars(httpRegistrar)
	httpServer := http.New(cfg, authMiddleware, corsMiddleware, v...)
	return httpServer
}
