// protoc --go_out=internal/infrastructure/client/roadmapclient/. --go-grpc_out=internal/infrastructure/client/roadmapclient/. internal/infrastructure/client/roadmapclient/proto/roadmap.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: internal/infrastructure/client/roadmapclient/proto/roadmap.proto

package roadmapclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoadmapService_Create_FullMethodName            = "/roadmapclient.RoadmapService/Create"
	RoadmapService_Delete_FullMethodName            = "/roadmapclient.RoadmapService/Delete"
	RoadmapService_GetByID_FullMethodName           = "/roadmapclient.RoadmapService/GetByID"
	RoadmapService_RegenerateNodeIDs_FullMethodName = "/roadmapclient.RoadmapService/RegenerateNodeIDs"
)

// RoadmapServiceClient is the client API for RoadmapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoadmapServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GetByIDResponse, error)
	RegenerateNodeIDs(ctx context.Context, in *RegenerateNodeIDsRequest, opts ...grpc.CallOption) (*RegenerateNodeIDsResponse, error)
}

type roadmapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoadmapServiceClient(cc grpc.ClientConnInterface) RoadmapServiceClient {
	return &roadmapServiceClient{cc}
}

func (c *roadmapServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, RoadmapService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roadmapServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, RoadmapService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roadmapServiceClient) GetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GetByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByIDResponse)
	err := c.cc.Invoke(ctx, RoadmapService_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roadmapServiceClient) RegenerateNodeIDs(ctx context.Context, in *RegenerateNodeIDsRequest, opts ...grpc.CallOption) (*RegenerateNodeIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateNodeIDsResponse)
	err := c.cc.Invoke(ctx, RoadmapService_RegenerateNodeIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoadmapServiceServer is the server API for RoadmapService service.
// All implementations must embed UnimplementedRoadmapServiceServer
// for forward compatibility.
type RoadmapServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	GetByID(context.Context, *GetByIDRequest) (*GetByIDResponse, error)
	RegenerateNodeIDs(context.Context, *RegenerateNodeIDsRequest) (*RegenerateNodeIDsResponse, error)
	mustEmbedUnimplementedRoadmapServiceServer()
}

// UnimplementedRoadmapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoadmapServiceServer struct{}

func (UnimplementedRoadmapServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRoadmapServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRoadmapServiceServer) GetByID(context.Context, *GetByIDRequest) (*GetByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedRoadmapServiceServer) RegenerateNodeIDs(context.Context, *RegenerateNodeIDsRequest) (*RegenerateNodeIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegenerateNodeIDs not implemented")
}
func (UnimplementedRoadmapServiceServer) mustEmbedUnimplementedRoadmapServiceServer() {}
func (UnimplementedRoadmapServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoadmapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoadmapServiceServer will
// result in compilation errors.
type UnsafeRoadmapServiceServer interface {
	mustEmbedUnimplementedRoadmapServiceServer()
}

func RegisterRoadmapServiceServer(s grpc.ServiceRegistrar, srv RoadmapServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoadmapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoadmapService_ServiceDesc, srv)
}

func _RoadmapService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoadmapServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoadmapService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoadmapServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoadmapService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoadmapServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoadmapService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoadmapServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoadmapService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoadmapServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoadmapService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoadmapServiceServer).GetByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoadmapService_RegenerateNodeIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateNodeIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoadmapServiceServer).RegenerateNodeIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoadmapService_RegenerateNodeIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoadmapServiceServer).RegenerateNodeIDs(ctx, req.(*RegenerateNodeIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoadmapService_ServiceDesc is the grpc.ServiceDesc for RoadmapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoadmapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roadmapclient.RoadmapService",
	HandlerType: (*RoadmapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RoadmapService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RoadmapService_Delete_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _RoadmapService_GetByID_Handler,
		},
		{
			MethodName: "RegenerateNodeIDs",
			Handler:    _RoadmapService_RegenerateNodeIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/infrastructure/client/roadmapclient/proto/roadmap.proto",
}
