services:
  proftwist:
    container_name: proftwist
    env_file: .env
    build:
      dockerfile: docker/Dockerfile
      context: ..
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - proftwist-network

  postgres:
    image: postgres:15
    container_name: proftwist_postgres
    ports:
      - "5434:5432"
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 3
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - proftwist-network

  pgweb:
    image: sosedoff/pgweb
    container_name: proftwist_pgweb
    ports:
      - "8082:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - postgres
    networks:
      - proftwist-network

  mongo:
    image: mongo:5.0
    container_name: proftwist_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    restart: on-failure
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/${MONGO_DB}?authSource=admin --quiet
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - mongo_data:/data/db
    networks:
      - proftwist-network

  mongo-express:
    image: mongo-express
    container_name: proftwist_mongo_express
    ports:
      - "8083:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - proftwist-network

volumes:
  postgres-data:
  mongo_data:

networks:
  proftwist-network:
