// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/F0urward/proftwist-backend/config"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/authclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/vkclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/aws"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/postgres"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/redis"
	"github.com/F0urward/proftwist-backend/internal/server/grpc"
	"github.com/F0urward/proftwist-backend/internal/server/http"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/auth"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/cors"
	grpc2 "github.com/F0urward/proftwist-backend/services/auth/delivery/grpc"
	http2 "github.com/F0urward/proftwist-backend/services/auth/delivery/http"
	"github.com/F0urward/proftwist-backend/services/auth/repository"
	"github.com/F0urward/proftwist-backend/services/auth/usecase"
)

// Injectors from wire.go:

func InitializeAuthHttpServer(cfg *config.Config) *http.HttpServer {
	authServiceClient := authclient.NewAuthClient(cfg)
	authMiddleware := auth.NewAuthMiddleware(authServiceClient, cfg)
	corsMiddleware := cors.NewCORSMiddleware(cfg)
	db := postgres.NewDatabase(cfg)
	postgresRepository := repository.NewAuthPostgresRepository(db)
	client := redis.NewClient(cfg)
	redisRepository := repository.NewAuthRedisRepository(client, cfg)
	minioClient := aws.NewClient(cfg)
	awsRepository := repository.NewAuthAWSRepository(minioClient)
	vkClient := vkclient.NewVKClient(cfg)
	vkWebapi := repository.NewVKAuthWebapi(vkClient)
	authUsecase := usecase.NewAuthUsecase(postgresRepository, redisRepository, awsRepository, vkWebapi, cfg)
	handlers := http2.NewAuthHandlers(authUsecase, cfg)
	httpRegistrar := http2.NewAuthHttpRegistrar(handlers)
	v := AllHttpRegistrars(httpRegistrar)
	httpServer := http.New(cfg, authMiddleware, corsMiddleware, v...)
	return httpServer
}

func InitializeAuthGrpcServer(cfg *config.Config) *grpc.GrpcServer {
	db := postgres.NewDatabase(cfg)
	postgresRepository := repository.NewAuthPostgresRepository(db)
	client := redis.NewClient(cfg)
	redisRepository := repository.NewAuthRedisRepository(client, cfg)
	minioClient := aws.NewClient(cfg)
	awsRepository := repository.NewAuthAWSRepository(minioClient)
	vkClient := vkclient.NewVKClient(cfg)
	vkWebapi := repository.NewVKAuthWebapi(vkClient)
	authUsecase := usecase.NewAuthUsecase(postgresRepository, redisRepository, awsRepository, vkWebapi, cfg)
	authServiceServer := grpc2.NewAuthServer(authUsecase)
	grpcRegistrar := grpc2.NewAuthGrpcRegistrar(authServiceServer)
	v := AllGrpcRegistrars(grpcRegistrar)
	grpcServer := grpc.New(cfg, v...)
	return grpcServer
}
