// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/F0urward/proftwist-backend/config"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/authclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/friendclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/vkclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/aws"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/postgres"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/redis"
	"github.com/F0urward/proftwist-backend/internal/metrics"
	"github.com/F0urward/proftwist-backend/internal/server/grpc"
	"github.com/F0urward/proftwist-backend/internal/server/http"
	logging2 "github.com/F0urward/proftwist-backend/internal/server/interceptor/logging"
	metrics3 "github.com/F0urward/proftwist-backend/internal/server/interceptor/metrics"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/auth"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/cors"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/logging"
	metrics2 "github.com/F0urward/proftwist-backend/internal/server/middleware/metrics"
	"github.com/F0urward/proftwist-backend/pkg/logger"
	grpc2 "github.com/F0urward/proftwist-backend/services/auth/delivery/grpc"
	http2 "github.com/F0urward/proftwist-backend/services/auth/delivery/http"
	"github.com/F0urward/proftwist-backend/services/auth/repository"
	"github.com/F0urward/proftwist-backend/services/auth/usecase"
)

// Injectors from wire.go:

func InitializeMetrics() metrics.Metrics {
	metricsMetrics := Metrics()
	return metricsMetrics
}

func InitializeAuthHttpServer(cfg *config.Config, log logger.Logger, mtrs metrics.Metrics) *http.HttpServer {
	authServiceClient := authclient.NewAuthClient(cfg)
	authMiddleware := auth.NewAuthMiddleware(authServiceClient, cfg)
	corsMiddleware := cors.NewCORSMiddleware(cfg)
	metricsMiddleware := metrics2.NewMetricsMiddleware(mtrs)
	loggingMiddleware := logging.NewLoggingMiddleware(log)
	db := postgres.NewDatabase(cfg)
	postgresRepository := repository.NewAuthPostgresRepository(db)
	client := redis.NewClient(cfg)
	redisRepository := repository.NewAuthRedisRepository(client, cfg)
	minioClient := aws.NewClient(cfg)
	awsRepository := repository.NewAuthAWSRepository(minioClient)
	vkClient := vkclient.NewVKClient(cfg)
	vkWebapi := repository.NewVKAuthWebapi(vkClient)
	friendServiceClient := friendclient.NewFriendClient(cfg)
	authUsecase := usecase.NewAuthUsecase(postgresRepository, redisRepository, awsRepository, vkWebapi, friendServiceClient, cfg)
	handlers := http2.NewAuthHandlers(authUsecase, cfg)
	httpRegistrar := http2.NewAuthHttpRegistrar(handlers)
	v := AllHttpRegistrars(httpRegistrar)
	httpServer := http.New(cfg, authMiddleware, corsMiddleware, metricsMiddleware, loggingMiddleware, v...)
	return httpServer
}

func InitializeAuthGrpcServer(cfg *config.Config, log logger.Logger, metrics4 metrics.Metrics) *grpc.GrpcServer {
	loggingUnaryServerInterceptor := logging2.NewLoggingUnaryServerInterceptor(log)
	metricsUnaryServerInterceptor := metrics3.NewMetricsUnaryServerInterceptor(metrics4)
	db := postgres.NewDatabase(cfg)
	postgresRepository := repository.NewAuthPostgresRepository(db)
	client := redis.NewClient(cfg)
	redisRepository := repository.NewAuthRedisRepository(client, cfg)
	minioClient := aws.NewClient(cfg)
	awsRepository := repository.NewAuthAWSRepository(minioClient)
	vkClient := vkclient.NewVKClient(cfg)
	vkWebapi := repository.NewVKAuthWebapi(vkClient)
	friendServiceClient := friendclient.NewFriendClient(cfg)
	authUsecase := usecase.NewAuthUsecase(postgresRepository, redisRepository, awsRepository, vkWebapi, friendServiceClient, cfg)
	authServiceServer := grpc2.NewAuthServer(authUsecase)
	grpcRegistrar := grpc2.NewAuthGrpcRegistrar(authServiceServer)
	v := AllGrpcRegistrars(grpcRegistrar)
	grpcServer := grpc.New(cfg, loggingUnaryServerInterceptor, metricsUnaryServerInterceptor, v...)
	return grpcServer
}
