// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package roadmap

import (
	"github.com/F0urward/proftwist-backend/config"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/authclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/chatclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/gigachatclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/roadmapinfoclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/mongo"
	"github.com/F0urward/proftwist-backend/internal/server/grpc"
	"github.com/F0urward/proftwist-backend/internal/server/http"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/auth"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/cors"
	grpc2 "github.com/F0urward/proftwist-backend/services/roadmap/delivery/grpc"
	http2 "github.com/F0urward/proftwist-backend/services/roadmap/delivery/http"
	"github.com/F0urward/proftwist-backend/services/roadmap/repository"
	"github.com/F0urward/proftwist-backend/services/roadmap/usecase"
)

// Injectors from wire.go:

func InitializeRoadmapHttpServer(cfg *config.Config) *http.HttpServer {
	authServiceClient := authclient.NewAuthClient(cfg)
	authMiddleware := auth.NewAuthMiddleware(authServiceClient, cfg)
	corsMiddleware := cors.NewCORSMiddleware(cfg)
	client := mongo.NewClient(cfg)
	database := mongo.NewDatabase(client, cfg)
	mongoRepository := repository.NewRoadmapMongoRepository(database)
	gigachatclientClient := gigachatclient.NewGigaChatClient(cfg)
	gigachatWebapi := repository.NewRoadmapGigaChatWebapi(gigachatclientClient)
	roadmapInfoServiceClient := roadmapinfoclient.NewRoadmapInfoClient(cfg)
	chatServiceClient := chatclient.NewChatClient(cfg)
	usecase := roadmap.NewRoadmapUsecase(mongoRepository, gigachatWebapi, roadmapInfoServiceClient, chatServiceClient)
	handlers := http2.NewRoadmapHandlers(usecase)
	httpRegistrar := http2.NewRoadmapHttpRegistrar(handlers)
	v := AllHttpRegistrars(httpRegistrar)
	httpServer := http.New(cfg, authMiddleware, corsMiddleware, v...)
	return httpServer
}

func InitializeRoadmapGrpcServer(cfg *config.Config) *grpc.GrpcServer {
	client := mongo.NewClient(cfg)
	database := mongo.NewDatabase(client, cfg)
	mongoRepository := repository.NewRoadmapMongoRepository(database)
	gigachatclientClient := gigachatclient.NewGigaChatClient(cfg)
	gigachatWebapi := repository.NewRoadmapGigaChatWebapi(gigachatclientClient)
	roadmapInfoServiceClient := roadmapinfoclient.NewRoadmapInfoClient(cfg)
	chatServiceClient := chatclient.NewChatClient(cfg)
	usecase := roadmap.NewRoadmapUsecase(mongoRepository, gigachatWebapi, roadmapInfoServiceClient, chatServiceClient)
	roadmapServiceServer := grpc2.NewRoadmapServer(usecase)
	grpcRegistrar := grpc2.NewRoadmapGrpcRegistrar(roadmapServiceServer)
	v := AllGrpcRegistrars(grpcRegistrar)
	grpcServer := grpc.New(cfg, v...)
	return grpcServer
}
