// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package roadmap

import (
	"github.com/F0urward/proftwist-backend/config"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/authclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/chatclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/gigachatclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/moderationclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/roadmapclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/roadmapinfoclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/mongo"
	"github.com/F0urward/proftwist-backend/internal/metrics"
	"github.com/F0urward/proftwist-backend/internal/server/grpc"
	"github.com/F0urward/proftwist-backend/internal/server/http"
	logging2 "github.com/F0urward/proftwist-backend/internal/server/interceptor/logging"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/auth"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/cors"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/logging"
	"github.com/F0urward/proftwist-backend/pkg/logger"
	http3 "github.com/F0urward/proftwist-backend/services/ai/delivery/http"
	"github.com/F0urward/proftwist-backend/services/ai/usecase"
	grpc2 "github.com/F0urward/proftwist-backend/services/roadmap/delivery/grpc"
	http2 "github.com/F0urward/proftwist-backend/services/roadmap/delivery/http"
	"github.com/F0urward/proftwist-backend/services/roadmap/repository"
	"github.com/F0urward/proftwist-backend/services/roadmap/usecase"
)

// Injectors from wire.go:

func InitializeMetrics() metrics.Metrics {
	metricsMetrics := Metrics()
	return metricsMetrics
}

func InitializeRoadmapHttpServer(cfg *config.Config, log logger.Logger, mtrs metrics.Metrics) *http.HttpServer {
	authServiceClient := authclient.NewAuthClient(cfg)
	authMiddleware := auth.NewAuthMiddleware(authServiceClient, cfg)
	corsMiddleware := cors.NewCORSMiddleware(cfg)
	loggingMiddleware := logging.NewLoggingMiddleware(log)
	client := mongo.NewClient(cfg)
	database := mongo.NewDatabase(client, cfg)
	mongoRepository := repository.NewRoadmapMongoRepository(database)
	gigachatclientClient := gigachatclient.NewGigaChatClient(cfg)
	gigachatWebapi := repository.NewRoadmapGigaChatWebapi(gigachatclientClient)
	roadmapInfoServiceClient := roadmapinfoclient.NewRoadmapInfoClient(cfg)
	chatServiceClient := chatclient.NewChatClient(cfg)
	moderationServiceClient := moderationclient.NewModerationClient(cfg)
	roadmapUsecase := roadmap.NewRoadmapUsecase(mongoRepository, gigachatWebapi, roadmapInfoServiceClient, chatServiceClient, authServiceClient, moderationServiceClient)
	handlers := http2.NewRoadmapHandlers(roadmapUsecase)
	httpRegistrar := http2.NewRoadmapHttpRegistrar(handlers)
	roadmapServiceClient := roadmapclient.NewRoadmapClient(cfg)
	aiUsecase := usecase.NewAIUsecase(cfg, roadmapServiceClient, roadmapInfoServiceClient)
	aiHandlers := http3.NewAIHandlers(aiUsecase)
	aiHttpRegistrar := http3.NewAIHttpRegistrar(aiHandlers)
	v := AllHttpRegistrars(httpRegistrar, aiHttpRegistrar)
	httpServer := http.New(cfg, authMiddleware, corsMiddleware, loggingMiddleware, v...)
	return httpServer
}

func InitializeRoadmapGrpcServer(cfg *config.Config, log logger.Logger, mtrs metrics.Metrics) *grpc.GrpcServer {
	loggingUnaryServerInterceptor := logging2.NewLoggingUnaryServerInterceptor(log)
	client := mongo.NewClient(cfg)
	database := mongo.NewDatabase(client, cfg)
	mongoRepository := repository.NewRoadmapMongoRepository(database)
	gigachatclientClient := gigachatclient.NewGigaChatClient(cfg)
	gigachatWebapi := repository.NewRoadmapGigaChatWebapi(gigachatclientClient)
	roadmapInfoServiceClient := roadmapinfoclient.NewRoadmapInfoClient(cfg)
	chatServiceClient := chatclient.NewChatClient(cfg)
	authServiceClient := authclient.NewAuthClient(cfg)
	moderationServiceClient := moderationclient.NewModerationClient(cfg)
	roadmapUsecase := roadmap.NewRoadmapUsecase(mongoRepository, gigachatWebapi, roadmapInfoServiceClient, chatServiceClient, authServiceClient, moderationServiceClient)
	roadmapServiceServer := grpc2.NewRoadmapServer(roadmapUsecase)
	grpcRegistrar := grpc2.NewRoadmapGrpcRegistrar(roadmapServiceServer)
	v := AllGrpcRegistrars(grpcRegistrar)
	grpcServer := grpc.New(cfg, loggingUnaryServerInterceptor, v...)
	return grpcServer
}
