// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package roadmapinfo

import (
	"github.com/F0urward/proftwist-backend/config"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/authclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/moderationclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/client/roadmapclient"
	"github.com/F0urward/proftwist-backend/internal/infrastructure/db/postgres"
	"github.com/F0urward/proftwist-backend/internal/metrics"
	"github.com/F0urward/proftwist-backend/internal/server/grpc"
	"github.com/F0urward/proftwist-backend/internal/server/http"
	logging2 "github.com/F0urward/proftwist-backend/internal/server/interceptor/logging"
	metrics3 "github.com/F0urward/proftwist-backend/internal/server/interceptor/metrics"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/auth"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/cors"
	"github.com/F0urward/proftwist-backend/internal/server/middleware/logging"
	metrics2 "github.com/F0urward/proftwist-backend/internal/server/middleware/metrics"
	"github.com/F0urward/proftwist-backend/pkg/logger"
	grpc2 "github.com/F0urward/proftwist-backend/services/roadmapinfo/delivery/grpc"
	http2 "github.com/F0urward/proftwist-backend/services/roadmapinfo/delivery/http"
	"github.com/F0urward/proftwist-backend/services/roadmapinfo/repository"
	"github.com/F0urward/proftwist-backend/services/roadmapinfo/usecase"
)

// Injectors from wire.go:

func InitializeMetrics() metrics.Metrics {
	metricsMetrics := Metrics()
	return metricsMetrics
}

func InitializeRoadmapInfoHttpServer(cfg *config.Config, log logger.Logger, mtrs metrics.Metrics) *http.HttpServer {
	authServiceClient := authclient.NewAuthClient(cfg)
	authMiddleware := auth.NewAuthMiddleware(authServiceClient, cfg)
	corsMiddleware := cors.NewCORSMiddleware(cfg)
	metricsMiddleware := metrics2.NewMetricsMiddleware(mtrs)
	loggingMiddleware := logging.NewLoggingMiddleware(log)
	db := postgres.NewDatabase(cfg)
	roadmapinfoRepository := repository.NewRoadmapInfoPostgresRepository(db)
	roadmapServiceClient := roadmapclient.NewRoadmapClient(cfg)
	moderationServiceClient := moderationclient.NewModerationClient(cfg)
	roadmapinfoUsecase := usecase.NewRoadmapInfoUsecase(roadmapinfoRepository, roadmapServiceClient, authServiceClient, moderationServiceClient)
	handlers := http2.NewRoadmapInfoHandlers(roadmapinfoUsecase)
	httpRegistrar := http2.NewRoadmapInfoHttpRegistrar(handlers)
	v := AllHttpRegistrars(httpRegistrar)
	httpServer := http.New(cfg, authMiddleware, corsMiddleware, metricsMiddleware, loggingMiddleware, v...)
	return httpServer
}

func InitializeRoadmapInfoGrpcServer(cfg *config.Config, log logger.Logger, mtrs metrics.Metrics) *grpc.GrpcServer {
	loggingUnaryServerInterceptor := logging2.NewLoggingUnaryServerInterceptor(log)
	metricsUnaryServerInterceptor := metrics3.NewMetricsUnaryServerInterceptor(mtrs)
	db := postgres.NewDatabase(cfg)
	roadmapinfoRepository := repository.NewRoadmapInfoPostgresRepository(db)
	roadmapServiceClient := roadmapclient.NewRoadmapClient(cfg)
	authServiceClient := authclient.NewAuthClient(cfg)
	moderationServiceClient := moderationclient.NewModerationClient(cfg)
	roadmapinfoUsecase := usecase.NewRoadmapInfoUsecase(roadmapinfoRepository, roadmapServiceClient, authServiceClient, moderationServiceClient)
	roadmapInfoServiceServer := grpc2.NewRoadmapInfoServer(roadmapinfoUsecase)
	grpcRegistrar := grpc2.NewRoadmapInfoGrpcRegistrar(roadmapInfoServiceServer)
	v := AllGrpcRegistrars(grpcRegistrar)
	grpcServer := grpc.New(cfg, loggingUnaryServerInterceptor, metricsUnaryServerInterceptor, v...)
	return grpcServer
}
